export const modulos = [
  {
    link: "shopify",
    image: "/imgs/shopify.webp",
    name: "Shopify",
    classes: [
      {
        id: "1",
        name: "1 Bienvenidos a la mentoria",
        image: "/imgs/shopify/cap1.webp",
        src: "https://youtu.be/dJWXITIL6Ic",
        video: true,
      },
      {
        id: "2",
        name: "2 Reglas del juego",
        image: "/imgs/shopify/cap2.webp",
        src: "/shopify/2-Reglas-del-juego.pdf",
        video: false,
      },
      {
        id: "3",
        name: "3 Marca y dominio",
        image: "/imgs/shopify/cap3.webp",
        src: "https://youtu.be/suxWVYeuC90",
        video: true,
      },
      {
        id: "4",
        name: "4 Configurando Shopify",
        image: "/imgs/shopify/cap4.webp",
        src: "https://youtu.be/x83D0FL5w3s",
        video: true,
        component: [
          {
            type: "png",
            src: "/shopify/complementos/Configurando-shopify-nosotros.png",
          },
          {
            type: "zip",
            src: "/shopify/complementos/Plantilla-optimizada-Mentoria-configurando-shopify.zip",
          },
        ],
      },
      {
        id: "5",
        name: "5 Politicas de la tienda",
        image: "/imgs/shopify/cap5.webp",
        src: "https://youtu.be/My7cSzkvtMo",
        video: true,
        component: {
          type: "pdf",
          src: "/shopify/complementos/Politicas-de-la-tienda.pdf",
        },
      },
      {
        id: "6",
        name: "6 Subiendo productos",
        image: "/imgs/shopify/cap6.webp",
        src: "https://youtu.be/NopUbdH45hM",
        video: true,
      },
      {
        id: "7",
        name: "7 Optimizando la plantilla",
        image: "/imgs/shopify/cap7.webp",
        src: "https://youtu.be/bQrnPJG6Zqg",
        video: true,
      },
      {
        id: "8",
        name: "8 Calculadora de precio",
        image: "/imgs/shopify/cap8.webp",
        src: "https://youtu.be/b4nQUoRVuVU",
        video: true,
        component: {
          type: "xlsx",
          src: "/shopify/complementos/CALCULADORA-DE-PRECIOS.xlsx",
        },
      },
      {
        id: "9",
        name: "9 Como crear colecciones",
        image: "/imgs/shopify/cap9.webp",
        src: "https://youtu.be/dU5QeAOXDrM",
        video: true,
      },
      {
        id: "10",
        name: "10 Complemento ventas pop",
        image: "/imgs/shopify/cap10.webp",
        src: "https://youtu.be/A4ixhh-VNK0",
        video: true,
      },
      {
        id: "11",
        name: "11 Agregar favicon",
        image: "/imgs/shopify/cap11.webp",
        src: "https://youtu.be/ozrgb2mdbks",
        video: true,
      },
    ],
    complements: [
      {
        type: "xlsx",
        src: "/shopify/complementos/CALCULADORA-DE-PRECIOS.xlsx",
      },
      {
        type: "png",
        src: "/shopify/complementos/Configurando-shopify-nosotros.png",
      },
      {
        type: "zip",
        src: "/shopify/complementos/Plantilla-optimizada-Mentoria-configurando-shopify.zip",
      },
      { type: "pdf", src: "/shopify/complementos/Politicas-de-la-tienda.pdf" },
    ],
  },
  {
    link: "liberacion",
    image: "/imgs/releasit.webp",
    name: "Liberación",
    classes: [
      {
        id: "1",
        name: "1 Oferta de calidad",
        image: "/imgs/releasit/cap1.webp",
        src: "/https://youtu.be/npA1ZeQdj2Y",
        video: true,
      },
      {
        id: "2",
        name: "2 Confirmación por whatsapp",
        image: "/imgs/releasit/cap2.webp",
        src: "https://youtu.be/BacjAYOubU0",
        video: true,
        complement: {
          type: "docx",
          src: "/releasit/complementos/Confirmacion-What.docx",
        },
      },
      {
        id: "3",
        name: "3 Confirmación por whatsapp",
        image: "/imgs/releasit/cap2.webp",
        src: "https://firebasestorage.googleapis.com/v0/b/next-firebase-a80b4.appspot.com/o/files%2F1%20Bienvenidos%20a%20la%20mentoria.mp4?alt=media&token=8fbd4701-f1c5-49ae-a460-caeb83507fed",
        video: true,
      },
    ],
    complements: [
      {
        type: "docx",
        src: "/releasit/complementos/Confirmacion-What.docx",
      },
    ],
  },
  {
    link: "facebook",
    image: "/imgs/facebook.webp",
    name: "Facebook",
    classes: [
      {
        id: "1",
        name: "1 Creando fanpage",
        image: "/imgs/facebook/cap1.webp",
        src: "https://youtu.be/eC9vbSt9veY",
        video: true,
      },
      {
        id: "2",
        name: "2 Conectando facebook con shopify",
        image: "/imgs/facebook/cap2.webp",
        src: "https://youtu.be/FBU0n73rCdU",
        video: true,
      },
      {
        id: "3",
        name: "3 Configurando gerente comercial",
        image: "/imgs/facebook/cap3.webp",
        src: "https://youtu.be/nma9Ycj2qkw",
        video: true,
      },
      {
        id: "4",
        name: "4 Como verificar el dominio",
        image: "/imgs/facebook/cap4.webp",
        src: "https://youtu.be/MpPKShU05vY",
        video: true,
      },
      {
        id: "5",
        name: "5 Metricas de facebook",
        image: "/imgs/facebook/cap5.webp",
        src: "https://youtu.be/YxMElvCfnKo",
        video: true,
      },
      {
        id: "6",
        name: "6 Estrategia 1 - Testeo Advantage",
        image: "/imgs/facebook/cap6.webp",
        src: "https://youtu.be/HbvrJYCTK2c",
        video: true,
      },
      {
        id: "7",
        name: "7 Estrategia 2 - Testeo Manual",
        image: "/imgs/facebook/cap7.webp",
        src: "https://youtu.be/5rk1iDMA2sA",
        video: true,
      },
    ],
  },
  {
    link: "dropi",
    image: "/imgs/dropi.webp",
    name: "Dropi",
    classes: [
      {
        id: "1",
        name: "1 Transportadoras",
        image: "/imgs/dropi/cap2.webp",
        src: "https://youtu.be/bW68ORFaxEs",
        video: true,
      },
      {
        id: "2",
        name: "2 Direcciones",
        image: "/imgs/dropi/cap2.webp",
        src: "https://youtu.be/RjSlRNF3XHI",
        video: true,
      },
    ],
  },
];
